### ISSUE TITLE
Please install a 2016 Cypress bundle in order to use the Cypress Validation Utility

### ISSUE THREAD

**Issue by gitouttatown** [projectcypress/cypress#588]
I have installed the bundles for 2016 and yet every time I click on the "Validation Utility" tab I get this error:
!Please install a 2016 Cypress bundle in order to use the Cypress Validation Utility
If you continue to receive this message, please email the Cypress Validation Utility team. Include the text of the message above, the upload settings you were using when you encountered the error, and a copy of the file you uploaded.

Upload a different file

---
It may be complaining that I did not first upload a file but I don't see any place where can upload file, *except* the screen where I upload a file for a particular test. When I upload there, it immediately evaluates against the requirements for that test.

On a related note: is there any user documentation for this release available? All I have seen is how to download and install it.
Thx

**Comment by ssayer** [comment]
Did you follow the install instructions and install a bundle for both the Cypress tool and validation utility? It requires two separate steps in the beta2 build (though this has been fixed for the final release)

**Comment by gitouttatown** [comment]
I had not seen that change to instructions added last Friday, so thank you. I just installed a bundle for the validation utility.  I still got the same error. I logged out of Cypress and back in, still the same. I restarted the Cypress VM, thinking it might force the new bundle data to be properly loaded. 

Here is the screen showing how I installed the bundle. Do you see any error?
![image](https://cloud.githubusercontent.com/assets/15641861/16818409/d6e2f4ee-4904-11e6-9af2-b85e12e48f16.png)

**Comment by ssayer** [comment]
No, that looks correct. I'll see if one of our release engineers can figure out what's going on.

**Comment by ssayer** [comment]
It looks like you're installing the 2016 bundle, which doesn't work in the beta2 version of the CVU. This is because the CMS IG for the 2017 reporting year was not released until late Monday and didn't make it in time for the release last week. The final version of the CVU released at the end of the month will work with the 2016 measures. This is not clear in the install instructions, so I'm sorry about the confusion. I'll update them to make sure others don't run into this before the final release

**Comment by ssayer** [comment]
I've updated the install instructions to note that it doesn't currently work with the 2016 measures. The final release will support both 2015 and 2016. Sorry about the confusion.

**Comment by gitouttatown** [comment]
Ok, I repeated the process, but loading the 2015 bundle. I had one error because, due to a typo, there were unused args at the end of the command. I think this caused Rake to abort.
![image](https://cloud.githubusercontent.com/assets/15641861/16819174/70786f14-4908-11e6-9807-b3d09da0800e.png)

I repeated the command again after that. Then I restarted the VM. Now it has stopped throwing the error.
Still looking for any user documentation for this version.
Thanks.
